// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace recipes_alexander_ccoa.Core.Models
{
    public partial class Motores
    {
        public int Id { get; set; }
        public string NoMotor { get; set; }
        public DateTime? Fecha { get; set; }
        public byte Statu { get; set; }
    }
}