// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace recipes_alexander_ccoa.Core.Models
{
    public partial class Recetas
    {
        public int Id { get; set; }
        public string Mezcla { get; set; }
        public DateTime Fecha { get; set; }
        public string InsT1 { get; set; }
        public decimal? Cant1 { get; set; }
        public string InsT2 { get; set; }
        public decimal? Cant2 { get; set; }
        public string InsT3 { get; set; }
        public decimal? Cant3 { get; set; }
        public string InsT4 { get; set; }
        public decimal? Cant4 { get; set; }
        public string InsT5 { get; set; }
        public decimal? Cant5 { get; set; }
        public string InsT6 { get; set; }
        public decimal? Cant6 { get; set; }
        public string InsT7 { get; set; }
        public decimal? Cant7 { get; set; }
        public string InsT8 { get; set; }
        public decimal? Cant8 { get; set; }
    }
}